import type { Metadata } from 'next'
import './globals.css'
import { headingFont, bodyFont } from '@/styles/fonts'
import { ReduxProvider } from '@/providers/redux-provider'
import { ThemeProvider } from '@/providers/theme-provider'
import { ToastProvider } from '@/providers/toast-provider'
import { KeyboardShortcuts } from '@/components/keyboard-shortcuts'
import { Clarity } from '@/components/analytics/clarity'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${headingFont.variable} ${bodyFont.variable} font-sans antialiased`}
      >
        {/* Blocking script to set theme before React hydrates - prevents FOUC */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const stored = localStorage.getItem('theme');
                  const theme = stored || (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
                  document.documentElement.classList.toggle('dark', theme === 'dark');
                } catch (e) {}
              })();
            `
          }}
        />
        <ReduxProvider>
          <ThemeProvider>
            <ToastProvider>
              <KeyboardShortcuts />
              <Clarity />
              {children}
            </ToastProvider>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
